### PR TITLE
issue44: adding webserver graceful shutdown

### LINKED ISSUE #44: Graceful Shutdown
## What happens?

he webserver does not terminate gracefully. There is no signal handler to do a graceful shutdown.

## What were you expecting to happen?

When the application receives a SIGTERM signal is does a graceful shutdown.

## Steps to reproduce: 

Start the application then send it a SIGTERM signal using the kill(1) command.

## Any errors, stacktrace, logs? 

N/A

## Environment:

* Runtime version(Java, Go, Python, etc): N/A
* Desktop OS/version: N/A

## Additional comments:

None.

### PR DESCRIPTION
**Pull request by wdoogz**
# Pull Request Template

## Description

Adding webserver declaration, moving error handling inside serve function to allow of graceful shutdown of http server. Ignoring the `ErrServerClosed` error, and adding proper logging to go with the change.

Output from HTTP Server when terminated via `kill -15 <pid>`
Screen Shot 2022-01-14 at 3 37 52 PM

Fixes #44 

## Type of change

Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)

## Environment

* Runtime version(Java, Go, Python, etc): Go

### CODE REVIEW

**Comment by seanmalloy** [comment]
@wdoogz can you rebase your branch to pull in the latest changes from master?

**Comment by wdoogz** [comment]
> @wdoogz can you rebase your branch to pull in the latest changes from master?

@seanmalloy Rebased!

**Review by ucantfixeverything — DISMISSED** [review]

File: main.go [hunk 1]
```diff
@@ -333,7 +349,11 @@ func serve(logger log.Logger, addr string, writers []writer, readers []reader) e
 		level.Debug(logger).Log("msg", "/read", "duration", duration) //nolint:errcheck
 	})
 
-	return http.ListenAndServe(addr, nil)
+	if err := srv.ListenAndServe(); err != http.ErrServerClosed {
+		level.Error(logger).Log("msg", "Failed to listen", "addr", addr, "err", err) //nolint:errcheck
```
Comment (seanmalloy) [inline main.go:353]: @wdoogz do we need to exit here if the web server fails to start listening?

Comment (seanmalloy) [reply main.go:353]: Looks like the exit used to be here before your change ... https://github.com/KohlsTechnology/prometheus_bigquery_remote_storage_adapter/pull/59/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261L144

Comment (wdoogz) [reply main.go:353]: I had to change the error handling from inside of the main function to inside of the serve function, and create a http server to be able to gracefully shutdown the server with this line.

https://github.com/KohlsTechnology/prometheus_bigquery_remote_storage_adapter/pull/59/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R243

I should add an exit at this line though, good catch.  I should add one at line 244 too.

**Comment by seanmalloy** [comment]
@wdoogz the code looks good now. Can you squash commits? I will merge once commits are squashed. Thanks!

**Review by seanmalloy — APPROVED** [review]
